"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path");
const generator=require("../scripts/build-kb-index.js"),corpus=require("../app/assets/js/kb-corpus.js"),ROOT=path.resolve(__dirname,"..");
function documentFor(id="KB-001",overrides={}){const second=id.startsWith("KB2-");return{id,edition:second?"second-edition":"first-edition",sequence:Number(id.split("-")[1]),title:"Electrical isolation",revision:"1",status:"approved",summary:"Safe isolation summary",purpose:"Explain battery isolation",difficulty:"basic",appliesTo:["Knaus"],sections:[{id:"main",heading:"Battery procedure",level:2,content:[{format:"plain-text",value:"Disconnect the negative terminal"}],tables:[],diagrams:[],warnings:[],notes:[],references:[]}],relatedKB:[],relatedChapters:[1],relatedManualPages:[12],tags:["electrical"],evidence:{classification:"manual-reference",confidence:"high"},provenance:{source:"Canonical source"},createdAt:"2026-07-27T00:00:00Z",updatedAt:"2026-07-27T00:00:00Z",...overrides}}
function recordFor(id="KB-001",doc=documentFor(id),overrides={}){const raw=Buffer.from(JSON.stringify(doc));return{id,edition:doc.edition,sequence:doc.sequence,title:doc.title,revision:"1",status:"approved",source:"Canonical",provenance:{origin:"source",method:"import",verifiedBy:"reviewer",verifiedAt:"2026-07-27T00:00:00Z"},checksum:generator.sha256(raw),contentPath:generator.expectedContentPath({id}),createdAt:"2026-07-27T00:00:00Z",updatedAt:"2026-07-27T00:00:00Z",relatedKbIds:[],relatedChapterIds:["01"],relatedManualPages:[12],tags:["electrical"],evidenceClassification:"manual-reference",confidenceLevel:"high",...overrides}}
const manifest=(records=[])=>({schemaVersion:1,generatedAt:"2026-07-27T00:00:00Z",expectedFirstEditionCount:250,expectedSecondEditionCount:25,records});
const reader=doc=>()=>Buffer.from(JSON.stringify(doc));
test("empty manifest and index retain expected count 275",()=>{assert.deepEqual(generator.validateManifest(manifest()),[]);const index=generator.buildIndex(manifest());assert.equal(index.expectedRecordCount,275);assert.equal(index.availableRecordCount,0)});
test("no placeholder KB records exist",()=>{assert.deepEqual(JSON.parse(fs.readFileSync(path.join(ROOT,"app/data/kb_manifest.json"))).records,[]);for(const dir of ["first-edition","second-edition"])assert.deepEqual(fs.readdirSync(path.join(ROOT,"app/corpus",dir)).filter(x=>x.endsWith(".json")),[])});
test("edition identifiers and canonical paths are enforced",()=>{for(const id of ["KB-001","KB-250","KB2-001","KB2-025"])assert.ok(generator.ID_PATTERN.test(id));assert.ok(!generator.ID_PATTERN.test("KB-251"));assert.equal(generator.expectedContentPath({id:"KB2-001"}),"app/corpus/second-edition/KB2-001.json")});
test("index sorting is deterministic",()=>{const a=documentFor("KB-001"),b=documentFor("KB-002"),records=[recordFor("KB-002",b),recordFor("KB-001",a)],read=file=>Buffer.from(JSON.stringify(file.includes("002")?b:a));assert.deepEqual(generator.buildIndex(manifest(records),read).records.map(x=>x.id),["KB-001","KB-002"])});
test("duplicate IDs are rejected",()=>{const doc=documentFor(),rec=recordFor("KB-001",doc);assert.match(generator.validateManifest(manifest([rec,rec]),reader(doc)).join(" "),/duplicate IDs/i)});
test("duplicate edition sequences are rejected",()=>{const a=documentFor("KB-001"),b=documentFor("KB-002",{sequence:1}),records=[recordFor("KB-001",a),recordFor("KB-002",b,{sequence:1})];assert.match(generator.validateManifest(manifest(records),file=>Buffer.from(JSON.stringify(file.includes("002")?b:a))).join(" "),/duplicate sequence/i)});
test("invalid edition is rejected",()=>{const doc=documentFor();assert.match(generator.validateManifest(manifest([recordFor("KB-001",doc,{edition:"second-edition"})]),reader(doc)).join(" "),/edition must/i)});
test("invalid checksum is rejected",()=>{const doc=documentFor();assert.match(generator.validateManifest(manifest([recordFor("KB-001",doc,{checksum:"bad"})]),reader(doc)).join(" "),/checksum/i)});
test("missing content file is rejected",()=>{const doc=documentFor();assert.match(generator.validateManifest(manifest([recordFor("KB-001",doc)]),()=>{throw Error()}).join(" "),/missing content file/i)});
test("related KB targets require a record unless pending",()=>{const doc=documentFor("KB-001",{relatedKB:[{id:"KB-002"}]});assert.match(generator.validateDocument(doc,recordFor("KB-001",doc),new Set(["KB-001"])).join(" "),/missing related KB/i);assert.deepEqual(generator.validateDocument({...doc,relatedKB:[{id:"KB-002",pending:true}]},recordFor("KB-001",doc),new Set(["KB-001"])),[])});
test("manual and chapter references are range checked",()=>{const doc=documentFor("KB-001",{relatedManualPages:[287],relatedChapters:[45]}),errors=generator.validateDocument(doc,recordFor("KB-001",doc),new Set(["KB-001"])).join(" ");assert.match(errors,/manual page/);assert.match(errors,/chapter/)});
test("unsafe content is rejected before rendering",()=>{const doc=documentFor("KB-001",{sections:[{id:"x",heading:"Unsafe",content:[{format:"controlled-html",value:"<script>alert(1)</script>"}]}]});assert.match(generator.validateDocument(doc,recordFor("KB-001",doc),new Set(["KB-001"])).join(" "),/unsafe/i);assert.throws(()=>corpus._safeDocument(doc,"KB-001"),/Unsafe/)});
test("empty runtime status and corpus statistics are graceful",async()=>{corpus._reset();await corpus.initialise({fetchJson:async url=>url.includes("manifest")?manifest():generator.buildIndex(manifest())});assert.equal(corpus.getStatus().status,"empty");assert.deepEqual(corpus.getStatistics(),{available:0,expected:275,firstEdition:0,secondEdition:0,approved:0})});
test("runtime searches ID, title and section content",async()=>{const doc=documentFor(),rec=recordFor("KB-001",doc),index=generator.buildIndex(manifest([rec]),reader(doc));corpus._reset();await corpus.initialise({fetchJson:async url=>url.includes("manifest")?manifest([rec]):index});for(const q of ["KB-001","isolation","negative terminal"])assert.equal(corpus.search(q)[0].id,"KB-001")});
test("runtime filters edition, status and tag",async()=>{const doc=documentFor(),rec=recordFor("KB-001",doc),index=generator.buildIndex(manifest([rec]),reader(doc));corpus._reset();await corpus.initialise({fetchJson:async url=>url.includes("manifest")?manifest([rec]):index});assert.equal(corpus.filter({edition:"first-edition",status:"approved",tag:"electrical"}).length,1);assert.equal(corpus.filter({edition:"second-edition"}).length,0)});
test("missing resources produce visible errors",async()=>{corpus._reset();const status=await corpus.initialise({fetchJson:async()=>{throw Error("missing index")}});assert.equal(status.status,"error");assert.match(status.message,/missing index/);await assert.rejects(()=>corpus.getDocument("KB-999"),/not found/)});
