const test=require("node:test"),assert=require("node:assert/strict");global.KnausRecordHistory=require("../app/assets/js/record-history.js");const api=require("../app/assets/js/owner-records.js");
const component="component:calira-evs";function setup(seed=[]){let state={schemaVersion:2,ownerRecords:structuredClone(seed),unrelated:{keep:true}};api._reset();api.initialise({getState:()=>state,setState:next=>state=next});return{state:()=>state}}
const base=(extra={})=>({type:"observation",title:"Observed battery state",status:"open",confidence:"high",provenance:"owner-observation",systemId:"electrical",componentIds:[component],occurredAt:"2026-01-01T10:00:00Z",...extra});
test("create, update, immutable reads, search, filter, timeline and histories",()=>{setup();const record=api.create(base(),{knownComponentIds:[component]});assert.equal(record.history.length,1);api.update(record.id,{status:"investigating",findings:"Voltage checked"},{knownComponentIds:[component]});const read=api.get(record.id);read.title="mutated";assert.notEqual(api.get(record.id).title,"mutated");assert.equal(api.search("voltage").length,1);assert.equal(api.filter({status:"investigating"}).length,1);assert.equal(api.getTimeline().length,1);assert.equal(api.getComponentHistory(component).length,1);assert.equal(api.getSystemHistory("electrical").length,1)});
test("invalid, duplicate and unsafe records are rejected",()=>{setup();assert.throws(()=>api.create(base({title:"",id:"bad"})));const item=api.create(base(),{knownComponentIds:[component]});assert.throws(()=>api.create({...base(),id:item.id}));assert.throws(()=>api.create(base({description:'<script>alert(1)</script>'})))});
test("fault lifecycle preserves suspected and confirmed cause",()=>{setup();const fault=api.create(base({type:"fault",title:"Intermittent supply",status:"open",suspectedCauses:["Loose connection"],confirmedCause:"",safetyClass:"caution"}),{knownComponentIds:[component]});for(const status of ["investigating","awaiting-parts","resolved","open","archived"]){status==="archived"?api.archive(fault.id):api.update(fault.id,{status},{knownComponentIds:[component]})}const result=api.get(fault.id);assert.deepEqual(result.suspectedCauses,["Loose connection"]);assert.equal(result.confirmedCause,"");assert.equal(result.safetyClass,"caution");assert.ok(result.history.length>=5)});
test("maintenance due dates and odometers are deterministic and tolerate absence",()=>{setup();const completed=api.create(base({type:"maintenance",title:"Fixture service",status:"completed",completedAt:"2026-01-15T10:00:00Z",intervalMonths:12,odometerCompleted:{value:50000,unit:"km"},intervalDistance:{value:10000,unit:"km"}}),{knownComponentIds:[component]});assert.equal(completed.nextDueDate,"2027-01-15");assert.deepEqual(completed.nextDueOdometer,{value:60000,unit:"km"});assert.doesNotThrow(()=>api.create(base({type:"maintenance",title:"No odometer",status:"deferred"}),{knownComponentIds:[component]}))});
test("measurements preserve units, chronology and links",()=>{setup();const first=api.create(base({type:"measurement",title:"12 V reading",measurements:[{category:"battery-voltage",value:12.7,unit:"V",measuredAt:"2026-01-02T10:00:00Z",componentId:component}],relatedFaultIds:["legacy-fault"]}),{knownComponentIds:[component]});assert.equal(first.measurements[0].unit,"V");assert.throws(()=>api.create(base({type:"measurement",title:"Bad unit",measurements:[{category:"pressure",value:2,unit:"made-up",measuredAt:"2026-01-02T10:00:00Z"}]})));assert.equal(api.getTimeline()[0].id,first.id)});
test("archive, restore and explicit deletion work",()=>{setup();const item=api.create(base(),{knownComponentIds:[component]});api.archive(item.id);assert.equal(api.get(item.id).archived,true);api.restore(item.id);assert.equal(api.get(item.id).archived,false);assert.throws(()=>api.remove(item.id));assert.equal(api.remove(item.id,{confirmed:true}),true)});
test("import preview detects conflicts and never overwrites silently",()=>{setup();const existing=api.create(base(),{knownComponentIds:[component]}),incoming={records:[{...existing,title:"Imported title"}]};const preview=api.previewImport(incoming,{knownComponentIds:[component]});assert.equal(preview.conflicts,1);api.importRecords(incoming,{conflict:"skip",knownComponentIds:[component]});assert.notEqual(api.get(existing.id).title,"Imported title");api.importRecords(incoming,{conflict:"copy",knownComponentIds:[component]});assert.equal(api.list().length,2);assert.equal(api.exportRecords().schemaVersion,2)});
test("storage write failures propagate without pretending success",()=>{api._reset();api.initialise({getState:()=>({ownerRecords:[]}),setState:()=>{throw Error("quota")}});assert.throws(()=>api.create(base()),/quota/)});
